var h;h||=typeof Immolate != 'undefined' ? Immolate : {};var aa=Object.assign({},h),ba="./this.program",ca=(a,b)=>{throw b;},da="object"==typeof window,r="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,w="",fa,ha,ia;
if(ea){var fs=require("fs"),ja=require("path");w=r?ja.dirname(w)+"/":__dirname+"/";fa=(a,b)=>{a=ka(a)?new URL(a):ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ia=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ha=(a,b,c,d=!0)=>{a=ka(a)?new URL(a):ja.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!h.thisProgram&&1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",
a=>{if(!("unwind"===a||a instanceof la||a.context instanceof la))throw a;});ca=(a,b)=>{process.exitCode=a;throw b;}}else if(da||r)r?w=self.location.href:"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src),w=w.startsWith("blob:")?"":w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1),fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},r&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)}),ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};h.print||console.log.bind(console);var x=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.thisProgram&&(ba=h.thisProgram);h.quit&&(ca=h.quit);var z;h.wasmBinary&&(z=h.wasmBinary);var ma,na=!1,A,B,D,oa,E,G,pa,qa,ra=[],sa=[],ta=[],ua=[];
function va(){var a=h.preRun.shift();ra.unshift(a)}var H=0,wa=null,I=null;function xa(a){h.onAbort?.(a);a="Aborted("+a+")";x(a);na=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://"),J;J="immolate.wasm";if(!ya(J)){var za=J;J=h.locateFile?h.locateFile(za,w):w+za}
function Aa(a){if(a==J&&z)return new Uint8Array(z);if(ia)return ia(a);throw"both async and sync fetching of the wasm failed";}function Ba(a){if(!z&&(da||r)){if("function"==typeof fetch&&!ka(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Aa(a));if(ha)return new Promise((b,c)=>{ha(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}
function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{x(`failed to asynchronously prepare wasm: ${d}`);xa(d)})}function Da(a,b){var c=J;z||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||ka(c)||ea||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x(`wasm streaming compile failed: ${e}`);x("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}
function la(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ea=a=>{for(;0<a.length;)a.shift()(h)},Fa=h.noExitRuntime||!0;class Ga{constructor(a){this.L=a-24}}
var Ha=0,Ia=0,Ja,L=a=>{for(var b="";B[a];)b+=Ja[B[a++]];return b},M={},N={},Ka={},O,Ma=a=>{throw new O(a);},P,R=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new P("Mismatched type converter count");for(var n=0;n<a.length;++n)Q(a[n],k[n])}a.forEach(function(k){Ka[k]=b});var e=Array(b.length),g=[],l=0;b.forEach((k,n)=>{N.hasOwnProperty(k)?e[n]=N[k]:(g.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(()=>{e[n]=N[k];++l;l===g.length&&d(e)}))});0===g.length&&d(e)};
function Na(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(a)){if(c.qa)return;throw new O(`Cannot register type '${d}' twice`);}N[a]=b;delete Ka[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(e=>e()))}function Q(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Na(a,b,c)}
var Oa=a=>{throw new O(a.F.M.K.name+" instance already deleted");},Pa=!1,Qa=()=>{},Ra=(a,b,c)=>{if(b===c)return a;if(void 0===c.P)return null;a=Ra(a,b,c.P);return null===a?null:c.na(a)},Sa={},S=[],Ta=()=>{for(;S.length;){var a=S.pop();a.F.Z=!1;a["delete"]()}},T,U={},Ua=(a,b)=>{if(void 0===b)throw new O("ptr should not be undefined");for(;a.P;)b=a.aa(b),a=a.P;return U[b]},Wa=(a,b)=>{if(!b.M||!b.L)throw new P("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.N)throw new P("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return Va(Object.create(a,{F:{value:b,writable:!0}}))},Va=a=>{if("undefined"===typeof FinalizationRegistry)return Va=b=>b,a;Pa=new FinalizationRegistry(b=>{b=b.F;--b.count.value;0===b.count.value&&(b.N?b.R.V(b.N):b.M.K.V(b.L))});Va=b=>{var c=b.F;c.N&&Pa.register(b,{F:c},b);return b};Qa=b=>{Pa.unregister(b)};return Va(a)};function Xa(){}
var Ya=(a,b)=>Object.defineProperty(b,"name",{value:a}),Za=(a,b,c)=>{if(void 0===a[b].O){var d=a[b];a[b]=function(...e){if(!a[b].O.hasOwnProperty(e.length))throw new O(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].O})!`);return a[b].O[e.length].apply(this,e)};a[b].O=[];a[b].O[d.ba]=d}},$a=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].O&&void 0!==h[a].O[c])throw new O(`Cannot register public name '${a}' twice`);Za(h,a,a);if(h.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].O[c]=b}else h[a]=b,void 0!==c&&(h[a].Ba=c)},ab=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function bb(a,b,c,d,e,g,l,k){this.name=a;this.constructor=b;this.U=c;this.V=d;this.P=e;this.oa=g;this.aa=l;this.na=k;this.sa=[]}var cb=(a,b,c)=>{for(;b!==c;){if(!b.aa)throw new O(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.aa(a);b=b.P}return a};
function db(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.F)throw new O(`Cannot pass "${eb(b)}" as a ${this.name}`);if(!b.F.L)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return cb(b.F.L,b.F.M.K,this.K)}
function fb(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);if(this.ea){var c=this.ta();null!==a&&a.push(this.V,c);return c}return 0}if(!b||!b.F)throw new O(`Cannot pass "${eb(b)}" as a ${this.name}`);if(!b.F.L)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.da&&b.F.M.da)throw new O(`Cannot convert argument of type ${b.F.R?b.F.R.name:b.F.M.name} to parameter type ${this.name}`);c=cb(b.F.L,b.F.M.K,this.K);if(this.ea){if(void 0===b.F.N)throw new O("Passing raw pointer to smart pointer is illegal");
switch(this.va){case 0:if(b.F.R===this)c=b.F.N;else throw new O(`Cannot convert argument of type ${b.F.R?b.F.R.name:b.F.M.name} to parameter type ${this.name}`);break;case 1:c=b.F.N;break;case 2:if(b.F.R===this)c=b.F.N;else{var d=b.clone();c=this.ua(c,gb(()=>d["delete"]()));null!==a&&a.push(this.V,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function hb(a,b){if(null===b){if(this.ha)throw new O(`null is not a valid ${this.name}`);return 0}if(!b.F)throw new O(`Cannot pass "${eb(b)}" as a ${this.name}`);if(!b.F.L)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.F.M.da)throw new O(`Cannot convert argument of type ${b.F.M.name} to parameter type ${this.name}`);return cb(b.F.L,b.F.M.K,this.K)}function ib(a){return this.fromWireType(G[a>>2])}
function jb(a,b,c,d,e,g,l,k,n,p,m){this.name=a;this.K=b;this.ha=c;this.da=d;this.ea=e;this.ra=g;this.va=l;this.la=k;this.ta=n;this.ua=p;this.V=m;e||void 0!==b.P?this.toWireType=fb:(this.toWireType=d?db:hb,this.S=null)}
var kb=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new P("Replacing nonexistent public symbol");void 0!==h[a].O&&void 0!==c?h[a].O[c]=b:(h[a]=b,h[a].ba=c)},lb=[],mb,nb=a=>{var b=lb[a];b||(a>=lb.length&&(lb.length=a+1),lb[a]=b=mb.get(a));return b},ob=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,h["dynCall_"+a])(b,...c)):b=nb(b)(...c);return b},pb=(a,b)=>(...c)=>ob(a,b,c),V=(a,b)=>{a=L(a);var c=a.includes("j")?pb(a,b):nb(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);
return c},qb,sb=a=>{a=rb(a);var b=L(a);W(a);return b},X=(a,b)=>{function c(g){e[g]||N[g]||(Ka[g]?Ka[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new qb(`${a}: `+d.map(sb).join([", "]));},tb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},ub=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function vb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].S)return!0;return!1}
function wb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ya(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function xb(a,b,c,d,e,g){var l=b.length;if(2>l)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,n=vb(b);c="void"!==b[0].name;d=[a,Ma,d,e,ub,b[0],b[1]];for(e=0;e<l-2;++e)d.push(b[e+2]);if(!n)for(e=k?1:2;e<b.length;++e)null!==b[e].S&&d.push(b[e].S);n=vb(b);e=b.length;var p="",m="";for(l=0;l<e-2;++l)p+=(0!==l?", ":"")+"arg"+l,m+=(0!==l?", ":"")+"arg"+l+"Wired";p=`\n        return function (${p}) {\n        if (arguments.length !== ${e-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e-2}');\n        }`;n&&(p+="var destructors = [];\n");var u=n?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+="var thisWired = classParam['toWireType']("+u+", this);\n");for(l=0;l<e-2;++l)p+="var arg"+l+"Wired = argType"+l+"['toWireType']("+u+", arg"+l+");\n",v.push("argType"+l);k&&(m="thisWired"+(0<m.length?", ":
"")+m);p+=(c||g?"var rv = ":"")+"invoker(fn"+(0<m.length?", ":"")+m+");\n";if(n)p+="runDestructors(destructors);\n";else for(l=k?1:2;l<b.length;++l)g=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==b[l].S&&(p+=`${g}_dtor(${g});\n`,v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [f,q]=[v,p+"}\n"];f.push(q);b=wb(f)(...d);return Ya(a,b)}
var yb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Ab=(a,b,c)=>{if(!(a instanceof Object))throw new O(`${c} with invalid "this": ${a}`);if(!(a instanceof b.K.constructor))throw new O(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.F.L)throw new O(`cannot call emscripten binding method ${c} on deleted object`);return cb(a.F.L,a.F.M.K,b.K)},Bb=[],Y=[],gb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
Bb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},Cb={name:"emscripten::val",fromWireType:a=>{if(!a)throw new O("Cannot use deleted val. handle = "+a);var b=Y[a];9<a&&0===--Y[a+1]&&(Y[a]=void 0,Bb.push(a));return b},toWireType:(a,b)=>gb(b),argPackAdvance:8,readValueFromPointer:ib,S:null},eb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Db=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(pa[c>>2])};case 8:return function(c){return this.fromWireType(qa[c>>
3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Eb=(a,b,c)=>{switch(b){case 1:return c?d=>A[d]:d=>B[d];case 2:return c?d=>D[d>>1]:d=>oa[d>>1];case 4:return c?d=>E[d>>2]:d=>G[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Fb=(a,b,c,d)=>{if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=
192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}},Gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Hb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Ib=(a,b)=>{var c=B,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Hb)return Hb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&
128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Jb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Kb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&oa[c];)++c;c<<=1;if(32<c-a&&Jb)return Jb.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=
D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Lb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},Mb=a=>2*a.length,Nb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Ob=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=
a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d},Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Qb={},Sb=()=>{if(!Rb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Qb)void 0===
Qb[b]?delete a[b]:a[b]=Qb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Rb=c}return Rb},Rb,Tb=a=>0===a%4&&(0!==a%100||0===a%400),Ub=[31,29,31,30,31,30,31,31,30,31,30,31],Vb=[31,28,31,30,31,30,31,31,30,31,30,31];function Wb(a){var b=Array(Gb(a)+1);Fb(a,b,0,b.length);return b}
for(var Xb=(a,b,c,d)=>{function e(f,q,t){for(f="number"==typeof f?f.toString():f||"";f.length<q;)f=t[0]+f;return f}function g(f,q){return e(f,q,"0")}function l(f,q){function t(F){return 0>F?-1:0<F?1:0}var y;0===(y=t(f.getFullYear()-q.getFullYear()))&&0===(y=t(f.getMonth()-q.getMonth()))&&(y=t(f.getDate()-q.getDate()));return y}function k(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function n(f){var q=f.X;for(f=new Date((new Date(f.Y+1900,0,1)).getTime());0<q;){var t=f.getMonth(),y=(Tb(f.getFullYear())?Ub:Vb)[t];if(q>y-f.getDate())q-=y-f.getDate()+1,f.setDate(1),11>t?f.setMonth(t+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+q);break}}t=new Date(f.getFullYear()+1,0,4);q=k(new Date(f.getFullYear(),0,
4));t=k(t);return 0>=l(q,f)?0>=l(t,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var p=G[d+40>>2];d={ya:E[d>>2],xa:E[d+4>>2],fa:E[d+8>>2],ia:E[d+12>>2],ga:E[d+16>>2],Y:E[d+20>>2],T:E[d+24>>2],X:E[d+28>>2],Ca:E[d+32>>2],wa:E[d+36>>2],za:p?p?Ib(p):"":""};c=c?Ib(c):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var m in p)c=c.replace(new RegExp(m,"g"),p[m]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");p={"%a":f=>u[f.T].substring(0,3),"%A":f=>u[f.T],"%b":f=>v[f.ga].substring(0,3),"%B":f=>v[f.ga],"%C":f=>g((f.Y+1900)/100|0,2),"%d":f=>
g(f.ia,2),"%e":f=>e(f.ia,2," "),"%g":f=>n(f).toString().substring(2),"%G":n,"%H":f=>g(f.fa,2),"%I":f=>{f=f.fa;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":f=>{for(var q=0,t=0;t<=f.ga-1;q+=(Tb(f.Y+1900)?Ub:Vb)[t++]);return g(f.ia+q,3)},"%m":f=>g(f.ga+1,2),"%M":f=>g(f.xa,2),"%n":()=>"\n","%p":f=>0<=f.fa&&12>f.fa?"AM":"PM","%S":f=>g(f.ya,2),"%t":()=>"\t","%u":f=>f.T||7,"%U":f=>g(Math.floor((f.X+7-f.T)/7),2),"%V":f=>{var q=Math.floor((f.X+7-(f.T+6)%7)/7);2>=(f.T+371-f.X-2)%7&&q++;if(q)53==q&&(t=(f.T+371-
f.X)%7,4==t||3==t&&Tb(f.Y)||(q=1));else{q=52;var t=(f.T+7-f.X-1)%7;(4==t||5==t&&Tb(f.Y%400-1))&&q++}return g(q,2)},"%w":f=>f.T,"%W":f=>g(Math.floor((f.X+7-(f.T+6)%7)/7),2),"%y":f=>(f.Y+1900).toString().substring(2),"%Y":f=>f.Y+1900,"%z":f=>{f=f.wa;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":f=>f.za,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(m in p)c.includes(m)&&(c=c.replace(new RegExp(m,"g"),p[m](d)));c=c.replace(/\0\0/g,"%");m=Wb(c);if(m.length>
b)return 0;A.set(m,a);return m.length-1},Yb=Array(256),Zb=0;256>Zb;++Zb)Yb[Zb]=String.fromCharCode(Zb);Ja=Yb;O=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};P=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Xa.prototype,{isAliasOf:function(a){if(!(this instanceof Xa&&a instanceof Xa))return!1;var b=this.F.M.K,c=this.F.L;a.F=a.F;var d=a.F.M.K;for(a=a.F.L;b.P;)c=b.aa(c),b=b.P;for(;d.P;)a=d.aa(a),d=d.P;return b===d&&c===a},clone:function(){this.F.L||Oa(this);if(this.F.$)return this.F.count.value+=1,this;var a=Va,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.F;a=a(c.call(b,d,{F:{value:{count:e.count,Z:e.Z,$:e.$,L:e.L,M:e.M,N:e.N,R:e.R}}}));a.F.count.value+=1;a.F.Z=!1;return a},["delete"](){this.F.L||
Oa(this);if(this.F.Z&&!this.F.$)throw new O("Object already scheduled for deletion");Qa(this);var a=this.F;--a.count.value;0===a.count.value&&(a.N?a.R.V(a.N):a.M.K.V(a.L));this.F.$||(this.F.N=void 0,this.F.L=void 0)},isDeleted:function(){return!this.F.L},deleteLater:function(){this.F.L||Oa(this);if(this.F.Z&&!this.F.$)throw new O("Object already scheduled for deletion");S.push(this);1===S.length&&T&&T(Ta);this.F.Z=!0;return this}});h.getInheritedInstanceCount=()=>Object.keys(U).length;
h.getLiveInheritedInstances=()=>{var a=[],b;for(b in U)U.hasOwnProperty(b)&&a.push(U[b]);return a};h.flushPendingDeletes=Ta;h.setDelayFunction=a=>{T=a;S.length&&T&&T(Ta)};
Object.assign(jb.prototype,{pa(a){this.la&&(a=this.la(a));return a},ka(a){this.V?.(a)},argPackAdvance:8,readValueFromPointer:ib,fromWireType:function(a){function b(){return this.ea?Wa(this.K.U,{M:this.ra,L:c,R:this,N:a}):Wa(this.K.U,{M:this,L:a})}var c=this.pa(a);if(!c)return this.ka(a),null;var d=Ua(this.K,c);if(void 0!==d){if(0===d.F.count.value)return d.F.L=c,d.F.N=a,d.clone();d=d.clone();this.ka(a);return d}d=this.K.oa(c);d=Sa[d];if(!d)return b.call(this);d=this.da?d.ma:d.pointerType;var e=Ra(c,
this.K,d.K);return null===e?b.call(this):this.ea?Wa(d.K.U,{M:d,L:e,R:this,N:a}):Wa(d.K.U,{M:d,L:e})}});qb=h.UnboundTypeError=((a,b)=>{var c=Ya(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
Y.push(0,1,void 0,1,null,1,!0,1,!1,1);h.count_emval_handles=()=>Y.length/2-5-Bb.length;
var ac={k:(a,b,c)=>{var d=new Ga(a);G[d.L+16>>2]=0;G[d.L+4>>2]=b;G[d.L+8>>2]=c;Ha=a;Ia++;throw Ha;},p:()=>{},x:(a,b,c,d)=>{b=L(b);Q(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(B[e])},S:null})},f:(a,b,c,d,e,g,l,k,n,p,m,u,v)=>{m=L(m);g=V(e,g);k&&=V(l,k);p&&=V(n,p);v=V(u,v);var f=ab(m);$a(f,function(){X(`Cannot construct ${m} due to unbound types`,[d])});R([a,b,c],d?[d]:[],q=>{q=q[0];if(d){var t=
q.K;var y=t.U}else y=Xa.prototype;q=Ya(m,function(...La){if(Object.getPrototypeOf(this)!==F)throw new O("Use 'new' to construct "+m);if(void 0===C.W)throw new O(m+" has no accessible constructor");var zb=C.W[La.length];if(void 0===zb)throw new O(`Tried to invoke ctor of ${m} with invalid number of parameters (${La.length}) - expected (${Object.keys(C.W).toString()}) parameters instead!`);return zb.apply(this,La)});var F=Object.create(y,{constructor:{value:q}});q.prototype=F;var C=new bb(m,q,F,v,t,
g,k,p);if(C.P){var K;(K=C.P).ja??(K.ja=[]);C.P.ja.push(C)}t=new jb(m,C,!0,!1,!1);K=new jb(m+"*",C,!1,!1,!1);y=new jb(m+" const*",C,!1,!0,!1);Sa[a]={pointerType:K,ma:y};kb(f,q);return[t,K,y]})},c:(a,b,c,d,e,g)=>{var l=tb(b,c);e=V(d,e);R([],[a],k=>{k=k[0];var n=`constructor ${k.name}`;void 0===k.K.W&&(k.K.W=[]);if(void 0!==k.K.W[b-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
k.K.W[b-1]=()=>{X(`Cannot construct ${k.name} due to unbound types`,l)};R([],l,p=>{p.splice(1,0,null);k.K.W[b-1]=xb(n,p,null,e,g);return[]});return[]})},a:(a,b,c,d,e,g,l,k,n)=>{var p=tb(c,d);b=L(b);b=yb(b);g=V(e,g);R([],[a],m=>{function u(){X(`Cannot call ${v} due to unbound types`,p)}m=m[0];var v=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&m.K.sa.push(b);var f=m.K.U,q=f[b];void 0===q||void 0===q.O&&q.className!==m.name&&q.ba===c-2?(u.ba=c-2,u.className=m.name,f[b]=u):(Za(f,
b,v),f[b].O[c-2]=u);R([],p,t=>{t=xb(v,t,m,g,l,n);void 0===f[b].O?(t.ba=c-2,f[b]=t):f[b].O[c-2]=t;return[]});return[]})},b:(a,b,c,d,e,g,l,k,n,p)=>{b=L(b);e=V(d,e);R([],[a],m=>{m=m[0];var u=`${m.name}.${b}`,v={get(){X(`Cannot access ${u} due to unbound types`,[c,l])},enumerable:!0,configurable:!0};v.set=n?()=>X(`Cannot access ${u} due to unbound types`,[c,l]):()=>{throw new O(u+" is a read-only property");};Object.defineProperty(m.K.U,b,v);R([],n?[c,l]:[c],f=>{var q=f[0],t={get(){var F=Ab(this,m,u+
" getter");return q.fromWireType(e(g,F))},enumerable:!0};if(n){n=V(k,n);var y=f[1];t.set=function(F){var C=Ab(this,m,u+" setter"),K=[];n(p,C,y.toWireType(K,F));ub(K)}}Object.defineProperty(m.K.U,b,t);return[]});return[]})},e:(a,b,c)=>{a=L(a);R([],[b],d=>{d=d[0];h[a]=d.fromWireType(c);return[]})},w:a=>Q(a,Cb),n:(a,b,c)=>{b=L(b);Q(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Db(b,c),S:null})},l:(a,b,c,d,e,g,l)=>{var k=tb(b,c);a=L(a);a=yb(a);e=V(d,e);$a(a,function(){X(`Cannot call ${a} due to unbound types`,
k)},b-1);R([],k,n=>{n=[n[0],null].concat(n.slice(1));kb(a,xb(a,n,null,e,g,l),b-1);return[]})},g:(a,b,c,d,e)=>{b=L(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var l=b.includes("unsigned")?function(k,n){return n>>>0}:function(k,n){return n};Q(a,{name:b,fromWireType:e,toWireType:l,argPackAdvance:8,readValueFromPointer:Eb(b,c,0!==d),S:null})},d:(a,b,c)=>{function d(g){return new e(A.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,
Float32Array,Float64Array][b];c=L(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{qa:!0})},i:a=>{Q(a,Cb)},m:(a,b)=>{b=L(b);var c="std::string"===b;Q(a,{name:b,fromWireType:function(d){var e=G[d>>2],g=d+4;if(c)for(var l=g,k=0;k<=e;++k){var n=g+k;if(k==e||0==B[n]){l=l?Ib(l,n-l):"";if(void 0===p)var p=l;else p+=String.fromCharCode(0),p+=l;l=n+1}}else{p=Array(e);for(k=0;k<e;++k)p[k]=String.fromCharCode(B[g+k]);p=p.join("")}W(d);return p},toWireType:function(d,e){e instanceof ArrayBuffer&&
(e=new Uint8Array(e));var g="string"==typeof e;if(!(g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new O("Cannot pass non-string to std::string");var l=c&&g?Gb(e):e.length;var k=$b(4+l+1),n=k+4;G[k>>2]=l;if(c&&g)Fb(e,B,n,l+1);else if(g)for(g=0;g<l;++g){var p=e.charCodeAt(g);if(255<p)throw W(n),new O("String has UTF-16 code units that do not fit in 8 bits");B[n+g]=p}else for(g=0;g<l;++g)B[n+g]=e[g];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:ib,
S(d){W(d)}})},j:(a,b,c)=>{c=L(c);if(2===b){var d=Kb;var e=Lb;var g=Mb;var l=k=>oa[k>>1]}else 4===b&&(d=Nb,e=Ob,g=Pb,l=k=>G[k>>2]);Q(a,{name:c,fromWireType:k=>{for(var n=G[k>>2],p,m=k+4,u=0;u<=n;++u){var v=k+4+u*b;if(u==n||0==l(v))m=d(m,v-m),void 0===p?p=m:(p+=String.fromCharCode(0),p+=m),m=v+b}W(k);return p},toWireType:(k,n)=>{if("string"!=typeof n)throw new O(`Cannot pass non-string to C++ string type ${c}`);var p=g(n),m=$b(4+p+b);G[m>>2]=p/b;e(n,m+4,p+b);null!==k&&k.push(W,m);return m},argPackAdvance:8,
readValueFromPointer:ib,S(k){W(k)}})},o:(a,b)=>{b=L(b);Q(a,{Aa:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},v:(a,b,c)=>B.copyWithin(a,b,b+c),h:(a,b)=>{var c=N[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${sb(a)}`,new O(a);a=c;a=a.readValueFromPointer(b);return gb(a)},t:()=>{xa("")},u:()=>{xa("OOM")},r:(a,b)=>{var c=0;Sb().forEach((d,e)=>{var g=b+c;e=G[a+4*e>>2]=g;for(g=0;g<d.length;++g)A[e++]=d.charCodeAt(g);A[e]=0;c+=d.length+1});return 0},s:(a,b)=>{var c=
Sb();G[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);G[b>>2]=d;return 0},q:(a,b,c,d)=>Xb(a,b,c,d)},Z=function(){function a(c){Z=c.exports;ma=Z.y;c=ma.buffer;h.HEAP8=A=new Int8Array(c);h.HEAP16=D=new Int16Array(c);h.HEAPU8=B=new Uint8Array(c);h.HEAPU16=oa=new Uint16Array(c);h.HEAP32=E=new Int32Array(c);h.HEAPU32=G=new Uint32Array(c);h.HEAPF32=pa=new Float32Array(c);h.HEAPF64=qa=new Float64Array(c);mb=Z.C;sa.unshift(Z.z);H--;h.monitorRunDependencies?.(H);0==H&&(null!==wa&&(clearInterval(wa),wa=
null),I&&(c=I,I=null,c()));return Z}var b={a:ac};H++;h.monitorRunDependencies?.(H);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return x(`Module.instantiateWasm callback failed with error: ${c}`),!1}Da(b,function(c){a(c.instance)});return{}}(),rb=a=>(rb=Z.A)(a),$b=a=>($b=Z.B)(a),bc=h._main=(a,b)=>(bc=h._main=Z.D)(a,b),W=a=>(W=Z.E)(a);h.dynCall_viijii=(a,b,c,d,e,g,l)=>(h.dynCall_viijii=Z.G)(a,b,c,d,e,g,l);h.dynCall_iiiiij=(a,b,c,d,e,g,l)=>(h.dynCall_iiiiij=Z.H)(a,b,c,d,e,g,l);
h.dynCall_iiiiijj=(a,b,c,d,e,g,l,k,n)=>(h.dynCall_iiiiijj=Z.I)(a,b,c,d,e,g,l,k,n);h.dynCall_iiiiiijj=(a,b,c,d,e,g,l,k,n,p)=>(h.dynCall_iiiiiijj=Z.J)(a,b,c,d,e,g,l,k,n,p);var cc;I=function dc(){cc||ec();cc||(I=dc)};
function ec(){function a(){if(!cc&&(cc=!0,h.calledRun=!0,!na)){Ea(sa);Ea(ta);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(fc){var b=bc;try{var c=b(0,0);Fa||(h.onExit?.(c),na=!0);ca(c,new la(c))}catch(d){d instanceof la||"unwind"==d||ca(1,d)}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),ua.unshift(b);Ea(ua)}}if(!(0<H)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();Ea(ra);0<H||(h.setStatus?
(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var fc=!0;h.noInitialRun&&(fc=!1);ec();
